# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-14 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Ответы',
                'verbose_name': 'Ответ',
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('main', models.BooleanField(default=False, verbose_name='Атрибут')),
                ('defines_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Attribute', verbose_name='Определяет_атрибут')),
            ],
            options={
                'verbose_name_plural': 'Атрибуты',
                'verbose_name': 'Атрибут',
                'db_table': 'attribute',
            },
        ),
        migrations.CreateModel(
            name='AttributeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Answer', verbose_name='Ответ')),
            ],
            options={
                'verbose_name_plural': 'Ответы и атрибуты',
                'verbose_name': 'Ответ-атрибут',
                'db_table': 'attribute_answer',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
                ('selected', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Attribute', verbose_name='Атрибут')),
            ],
            options={
                'verbose_name_plural': 'Значения атрибутов',
                'verbose_name': 'Значение атрибута',
                'db_table': 'attribute_value',
            },
        ),
        migrations.CreateModel(
            name='ObjectsAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Атрибуты объектов',
                'verbose_name': 'Атрибут объекта',
                'db_table': 'objects_attributes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, verbose_name='Teкст')),
                ('type', models.IntegerField(choices=[(0, 'Выберете ответ'), (1, 'Напишите число')], verbose_name='Тип')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'verbose_name': 'Вопрос',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Answer', verbose_name='Выбранный ответ-условие')),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next', to='project.Question', verbose_name='Следующий вопрос')),
                ('not_ask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_ask', to='project.Question', verbose_name='Не спрашивать')),
            ],
            options={
                'verbose_name_plural': 'Следующие вопросы',
                'verbose_name': 'Следующий вопрос',
                'db_table': 'question_order',
            },
        ),
        migrations.CreateModel(
            name='RulesAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.IntegerField(choices=[(0, 'И'), (1, 'ИЛИ')], verbose_name='Операция')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='project.AttributeValue', verbose_name='Результат')),
                ('value1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value1', to='project.AttributeValue', verbose_name='Условие 1')),
                ('value2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value2', to='project.AttributeValue', verbose_name='Условие 2')),
            ],
            options={
                'verbose_name_plural': 'Правила атрибутов',
                'verbose_name': 'Правило атрибутов',
                'db_table': 'rules_attr',
            },
        ),
        migrations.CreateModel(
            name='SystemObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('attributes', models.ManyToManyField(blank=True, through='project.ObjectsAttribute', to='project.AttributeValue', verbose_name='Атрибуты')),
            ],
            options={
                'verbose_name_plural': 'Объекты',
                'verbose_name': 'Объект',
                'db_table': 'object',
            },
        ),
        migrations.AddField(
            model_name='objectsattribute',
            name='sys_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.SystemObject'),
        ),
        migrations.AddField(
            model_name='objectsattribute',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.AttributeValue'),
        ),
        migrations.AddField(
            model_name='attributeanswer',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.AttributeValue', verbose_name='Значение атрибута'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='project.Question', verbose_name='Вопрос'),
        ),
    ]
