# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-17 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20151117_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalue',
            old_name='selected',
            new_name='ifselected',
        ),
    ]
