# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-18 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_question_if_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionorder',
            name='not_ask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='not_ask', to='project.Question', verbose_name='Не спрашивать'),
        ),
    ]
